export const GAME_FIELDS = [
  'alternative_names.*',
  'category',
  'cover.*',
  'first_release_date',
  'franchise.*',
  'franchises.*',
  'game_localizations.*',
  'genres.*',
  'keywords.*',
  'name',
  'platforms.*',
  'release_dates.*',
  'screenshots.*',
  'slug',
  'storyline',
  'summary',
  'themes.*',
  'url',
  'videos.*',
] as const;

export const GAME_LOCALIZATION_FIELDS = [
  'checksum',
  'cover.*',
  'created_at',
  'game',
  'name',
  'region.*',
  'updated_at',
] as const;


export const PLATFORM_FIELDS = [
  'abbreviation',
  'alternative_name',
  'category',
  'checksum',
  'created_at',
  'generation',
  'name',
  'platform_family',
  'platform_logo.*',
  'platform_type',
  'slug',
  'summary',
  'updated_at',
  'url',
  'versions',
  'websites',
] as const;
